-- Seed jobs (no employer_id — system listings)
insert into jobs (id, employer_id, title, company, location, type, salary, description, requirements, required_skills, posted_at) values
  ('seed-1',  null, 'Frontend Engineer',   'Stripe',      'San Francisco, CA', 'Full-time', '$140k – $180k', 'Build beautiful, fast UIs.',                                                   '3+ years React experience.',                             array['React','TypeScript','CSS'],                      '2026-03-10T00:00:00Z'),
  ('seed-2',  null, 'Backend Engineer',    'Notion',      'New York, NY',      'Full-time', '$130k – $170k', 'Scale our backend services.',                                                  'Experience with Node.js or Go.',                         array['Node.js','PostgreSQL','Redis'],                   '2026-03-11T00:00:00Z'),
  ('seed-3',  null, 'Product Designer',    'Linear',      'Remote',            'Remote',    '$110k – $150k', 'Design intuitive product experiences.',                                        'Strong portfolio required.',                             array['Figma','Prototyping','User Research'],             '2026-03-09T00:00:00Z'),
  ('seed-4',  null, 'Data Scientist',      'Airbnb',      'Seattle, WA',       'Full-time', '$150k – $190k', 'Drive insights from large datasets.',                                          'PhD or equivalent experience preferred.',                array['Python','SQL','Machine Learning'],                '2026-03-08T00:00:00Z'),
  ('seed-5',  null, 'DevOps Engineer',     'Vercel',      'Remote',            'Remote',    '$120k – $160k', 'Maintain and improve our CI/CD infrastructure.',                               '2+ years with Kubernetes and AWS.',                      array['Kubernetes','AWS','Terraform'],                   '2026-03-07T00:00:00Z'),
  ('seed-6',  null, 'iOS Developer',       'Duolingo',    'Pittsburgh, PA',    'Full-time', '$125k – $165k', 'Build delightful mobile learning experiences.',                                'Swift expertise required.',                              array['Swift','UIKit','SwiftUI'],                        '2026-03-06T00:00:00Z'),
  ('seed-7',  null, 'Marketing Manager',   'Figma',       'San Francisco, CA', 'Full-time', '$100k – $130k', 'Lead go-to-market campaigns.',                                                 '5+ years B2B SaaS marketing.',                           array['Content Strategy','SEO','Analytics'],             '2026-03-05T00:00:00Z'),
  ('seed-8',  null, 'ML Engineer',         'Hugging Face','Remote',            'Remote',    '$160k – $200k', 'Train and deploy large language models.',                                      'Deep learning research background.',                     array['PyTorch','Python','Transformers'],                '2026-03-04T00:00:00Z'),
  ('seed-9',  null, 'Technical Recruiter', 'Rippling',    'New York, NY',      'Contract',  '$70k – $90k',  'Source and close top engineering talent.',                                     '2+ years technical recruiting.',                         array['Sourcing','ATS','Interviewing'],                  '2026-03-03T00:00:00Z'),
  ('seed-10', null, 'Security Engineer',   'Cloudflare',  'Austin, TX',        'Full-time', '$145k – $185k', 'Protect infrastructure at global scale.',                                       'Experience with network security and pen testing.',      array['Network Security','Penetration Testing','Go'],    '2026-03-02T00:00:00Z'),
  ('seed-11', null, 'Android Developer',   'Cash App',    'San Francisco, CA', 'Full-time', '$130k – $170k', 'Build payments features for millions of users.',                               'Strong Kotlin skills.',                                  array['Kotlin','Jetpack Compose','Android SDK'],         '2026-03-01T00:00:00Z'),
  ('seed-12', null, 'QA Engineer',         'Brex',        'Remote',            'Part-time', '$60k – $80k',  'Own test coverage across web and mobile.',                                     'Experience with Cypress or Playwright.',                  array['Cypress','Playwright','Test Automation'],         '2026-02-28T00:00:00Z')
on conflict (id) do nothing;
